version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
  python:
    image: python:3.8
    depends_on:
      - mysql
  centos:
    image: centos:7
    depends_on:
      - nginx
      - mysql
      - python
